version: "3.9"

x-common-restart: &common-restart
  restart: unless-stopped

services:
  prometheus:
    image: prom/prometheus:latest
    <<: *common-restart
    env_file: .env
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    ports:
      - "9090:9090"

  alertmanager:
    image: prom/alertmanager:v0.28.0
    <<: *common-restart
    volumes:
      - ./alertmanager/config.yml:/etc/alertmanager/config.yml:ro
      - alertmanager_data:/alertmanager
    command:
      - '--config.file=/etc/alertmanager/config.yml'
    ports:
      - "9093:9093"

  grafana:
    image: grafana/grafana:10.0.5
    <<: *common-restart
    env_file: .env
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - alertmanager

  node-exporter:
    image: prom/node-exporter:v1.7.0
    <<: *common-restart
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($|/)'

  digitalocean-exporter:
    image: metalmatze/digitalocean_exporter:0.6.1
    restart: unless-stopped
    environment:
      DIGITALOCEAN_TOKEN: "${DO_API_TOKEN_READONLY}"   # cria esse env no .env
    ports:
      - "9212:9212"

  loki:
    image: grafana/loki:2.9.0
    restart: unless-stopped
    entrypoint: ["/bin/sh", "-c"]
    command: >
      mkdir -p /loki/index /loki/cache /loki/chunks /loki/compactor /loki/boltdb-shipper-compactor /wal &&
      exec /usr/bin/loki -config.file=/etc/loki/loki-config.yaml
    volumes:
      - ./config/loki-config.yaml:/etc/loki/loki-config.yaml:ro
      - loki_data:/loki
      - loki_wal:/wal
    ports:
      - "3100:3100"


  promtail:
    image: grafana/promtail:2.9.0
    restart: unless-stopped
    volumes:
      - /var/log:/var/log:ro
      - ./config/promtail-config.yaml:/etc/promtail/config.yaml:ro
    command: -config.file=/etc/promtail/config.yaml
    depends_on:
      - loki

volumes:
  prometheus_data:
  alertmanager_data:
  grafana_data:
  loki_data:
  loki_wal:
