version: "3.9"

x-common-restart: &common-restart
  restart: unless-stopped

services:
  prometheus:
    image: prom/prometheus:latest
    <<: *common-restart
    env_file: .env
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    ports:
      - "9090:9090"

  alertmanager:
    image: prom/alertmanager:v0.28.0
    <<: *common-restart
    volumes:
      - ./alertmanager/config.yml:/etc/alertmanager/config.yml:ro
      - alertmanager_data:/alertmanager
    command:
      - '--config.file=/etc/alertmanager/config.yml'
    ports:
      - "9093:9093"

  grafana:
    image: grafana/grafana:10.0.5
    <<: *common-restart
    env_file: .env
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - alertmanager

  node-exporter:
    image: prom/node-exporter:v1.7.0
    <<: *common-restart
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($|/)'

volumes:
  prometheus_data:
  alertmanager_data:
  grafana_data:
