server:
  http_listen_port: 9411

distributor:
  receivers: []

storage:
  trace:
    backend: s3
  s3:
    endpoint: ${SPACES_ENDPOINT}
    bucket: ${SPACES_BUCKET}
    access_key: ${SPACES_KEY}
    secret_key: ${SPACES_SECRET}
    region: ${SPACES_REGION}
    s3forcepathstyle: true

ingesters:
  wal:
    dir: /var/tempo/wal

pipeline:
  receivers: []
