environment        = "staging"
droplet_name       = "pyron-monitor-stack"
droplet_size       = "s-2vcpu-4gb"
spaces_bucket_name = "pyron-monitor-stack"
spaces_region      = "fra1"
spaces_endpoint    = "https://fra1.digitaloceanspaces.com"
ssh_key_name       = "monitor-stack-pipeline"
