environment        = "staging"
droplet_name       = "pyron-monitor-stack"
droplet_size       = "s-2vcpu-4gb"
spaces_bucket_name = "iac-pyron-monitor-stack"
spaces_region      = "fra1"
spaces_endpoint    = "https://fra1.digitaloceanspaces.com"
ssh_key_name       = "monitor-stack-pipeline"
do_project_id      = "4d35904f-7b87-4b19-9661-c521590ea17c"
